name: deploy_firebase_hosting
on:
  push:
    branches:
      - master
jobs:
  deploy_firebase_hosting:
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
	# ポイント１
	# ↓↓↓ node_modulesはgit管理していないと思いますので、ここで、nodeモジュールを取得するコマンドをjobとして設定します。
      - name: Install Dependencies # ← コマンド識別名
        run: yarn install　# ← 実際のコマンド
	# ポイント２
	# ↓↓↓ ビルドファイルを作成するためのコマンド
      - name: Build
        run: yarn run build
	# ポイント３
	# ↓↓↓ Firebaseのデプロイコマンドここに先ほど控えたトークンを貼り付けます
      - name: Deploy to Firebase
        run: yarn deploy --token=${{1//0eRNc5EuzEogZCgYIARAAGA4SNwF-L9IrfpSseV8yVIAltJ7b4xCqeEmpkmcGhNzV_eHqyype7bR9n8qQTjPrkre7KqFyz1iDV00}}
